### ISSUE TITLE
Add support for new gamepass feature

### ISSUE THREAD

**Issue by laureegrd** [LMH01/MGT2_Mod_Tool#116]
A recent update to MGT2 added gamepass as a feature for platforms, with the default ones sometimes having a `[GAMEPASS]` parameter that, if I'm not mistaken, correlates to the minimum amount of games (usually 10) that should be made available in that platform's gamepass (I haven't reached 2004 in the game yet, so I'm not sure).

Adding platforms with the mod tool should allow for a `GAMEPASS = "10"` parameter. As of right now, added platforms would not contain that parameter? making them either default to 0 or not allow for gamepass at all (again, haven't played enough to know what happens with platforms that don't have it set).

**Comment by LMH01** [comment]
This has been implemented but the tool tip text currently states that I don't know exactly what it does.
This tool tip text will be updated when I know for sure what the usage of that value is.

**Comment by LMH01** [comment]
Added in v4.8.0
