### ISSUE TITLE
Publisher dependency breaks when importing said publisher at the same time

### ISSUE THREAD

**Issue by laureegrd** [LMH01/MGT2_Mod_Tool#122]
(4.9.0-beta2)

Importing a new publisher while also importing a npc_ip that requires it causes the missing dependency window to pop up. The dependency check doesn't realize that this publisher will be added, and it's not missing.

Furthermore, if at the same time other publishers are being modified or replaced (and thus missing from the game files at the moment that the dependency check happens) they will not show on the dependency replacement window. As a result, if all publishers are being modified at the same time (renaming them all for example), the dependency replacement window will be empty, forcing the user to cancel the import (or continuing and meeting up with a crash when it tries to randomly select from the empty list).

![image](https://user-images.githubusercontent.com/9524250/221851095-306b1e9c-4804-4dae-801a-816e00101629.png)

EDIT: Removed wrong solution regarding import order of the toml files. I had made a mistake in my test and the error still occurs regardless of toml file names.

**Comment by LMH01** [comment]
Related to #86

**Comment by laureegrd** [comment]
I think I found something weird happening. I separated my mod into two parts to facilitate testing. The first part renames all publishers, platforms and Npc IPs. Works perfectly.

The second part has two files, one modifying one of those Npc IPs to now use a new publisher, one adding said publisher. The tool seems to only be loading one of the mods (the NPC IP), thus throwing the error because it can't find the new publisher.

Im constantly manually deleting the temp folder between steps to avoid leftover files from being read by the tool.

```
Toml file found: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\new_npc_ips.toml
Toml file found: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\new_publishers.toml
Search for .toml files complete. Took 0.84 seconds!
Total .toml files found: 2
Analyzing .toml files to determine if they contain mods
Reading toml file: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\new_npc_ips.toml
Reading toml file: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\new_publishers.toml
Found files that contain mods: 2
Single mod files: 0
Bundled mod files: 2
Searching toml files for mods
Total number of mods found: 1
Already added: 0
Incompatible: 0
Duplicated: 0
Unique: 1
Replace: 0
Modify: 1
Add: 0
Import process has been canceled
```

I cancel and remove the npc_ip file from inside that .zip, then the publisher file is read properly and lets me add it.

```
Toml file found: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\new_publishers.toml
Search for .toml files complete. Took 0.63 seconds!
Total .toml files found: 1
Analyzing .toml files to determine if they contain mods
Reading toml file: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\new_publishers.toml
Found files that contain mods: 1
Single mod files: 0
Bundled mod files: 1
Searching toml files for mods
Found mod: publisher - Spectrum Holobyte
Total number of mods found: 1
Already added: 0
Incompatible: 0
Duplicated: 0
Unique: 1
Replace: 0
Modify: 0
Add: 1
Checking assets folder(s)
Checking for conflicts
Editing import map
Checking dependencies
Setting new mod ids
Constructing contents
Content construction took 0.00 seconds!
Checking images
Checking for existing images
Copying images for content Spectrum Holobyte
All content (1) of type publisher has been successfully added to the .txt file after 0.00 seconds!
Import process has been completed after 3.30 seconds!
```

Then I tried deleting the publisher file from the .zip, and re-adding the npc_ip one, but I'm met with an error that it can't find the renamed NPC IP (probably a different bug)

**Comment by laureegrd** [comment]
> This should not be necessary because the temp folder should automatically be deleted.

This is not happening when import is cancelled or it fails, I'm always manually deleting it as I noticed leftover files being read sometimes between attempts.

**Comment by laureegrd** [comment]
Adding an entirely new NPC IP alongside an entirely new publisher still causes the issue, so it's not directly related #86 (could still be in some indirect way?).

[new_content.zip](https://github.com/LMH01/MGT2_Mod_Tool/files/10850693/new_content.zip)

**Comment by laureegrd** [comment]
I am dumb. It was a capitalization error by my part. 🥲
