### ISSUE TITLE
Temp folder not getting deleted

### ISSUE THREAD

**Issue by laureegrd** [LMH01/MGT2_Mod_Tool#125]
When an import fails or simply is cancelled, the temp folder stays there. This has the unexpected side effect of keeping files that may not be in the .zip the next time you import it.

To reproduce:
- Import a .zip.
- Click yes on the first prompt to scan for mods.
- Cancel import after it finds them.
- Temp folder is still there.

**Comment by LMH01** [comment]
Implemented in v4.9.0
