### ISSUE TITLE
Add support for <R> tag in DevLegends file

### ISSUE THREAD

**Issue by LMH01** [LMH01/MGT2_Mod_Tool#136]
Message from steam by TitanKämpfer:

"While checking the game's code, I found out that "\<R\>" is also a legit tag for DevLegends.txt. This will spawn legendary researchers. (Also tested it ingame and it spawned a researcher with the famous perk and researach skill of 85.1)
This could be added to the editor!"

**Comment by SilverBackSpartan** [comment]
Oh nice - when can we use this feature?

**Comment by LMH01** [comment]
> Oh nice - when can we use this feature?

When I have some time to implement it, I don't want to specify a specific release date at the moment.
