### ISSUE TITLE
Maximale Stufe

### ISSUE THREAD

**Issue by Joti17** [LMH01/MGT2_Mod_Tool#154]
Kannst du machen, dass die zahl bei z.B. Tech reinschreiben kann und nicht die ganze Zeit denn hoch knopf drücken muss und es kein Limit für die höhe des Tech etc. Levels gibt?

![Screenshot 2023-07-11 132427](https://github.com/LMH01/MGT2_Mod_Tool/assets/111738035/9727f636-555c-43b0-a6c9-a26076460c5a)

**Comment by LMH01** [comment]
Das geht wenn du in die Einstellungen gehst (Unter File oben links), dort auf den Knopf "Configure safety features" clickst und in dem sich öffnenden Fenster die Box bei "Unlock spinners" anklickst. Wenn du die Einstellungen speicherst, sind die Spinner im folgenden freigeschaltet.
