### ISSUE TITLE
Manual input

### ISSUE THREAD

**Issue by ilia-21** [LMH01/MGT2_Mod_Tool#158]
**Is your feature request related to a problem? Please describe.**
I think it is not very convenient to enter numbers by pressing the up or down button, it is very inconvenient when I for example add hardware for the year 2050 - I have to scroll from the beginning 

**Describe the solution you'd like**
Make the fields for entering numbers editable by the keyboard

**Describe alternatives you've considered**
I'm not very familiar with java, but I'm pretty sure the UI library you used should have the function I described

**Additional context**
![06-04-2024 212452 (javaw)](https://github.com/LMH01/MGT2_Mod_Tool/assets/67857080/f30f2587-111f-4c43-bf40-cd3b395c51ef)

**Comment by LMH01** [comment]
Hello, thanks for your feature request. The feature you requested can already be enabled: Navigate to File -> Settings -> Configure safety features -> tick the check box next to `Unlock spinners` -> close the window and save the settings.

The reason I hid that behind this checkbox was the following: I have minimum and maximum values set and If a value is manually entered that is outside of that bound the entered value will automatically be changed back to an allowed value. I thought that this might lead to confusion, so I decided to lock the spinners.
