### ISSUE TITLE
Somewhere to share the edits we make on MGT2

### ISSUE THREAD

**Issue by Spontini** [LMH01/MGT2_Mod_Tool#17]
It'd be cool if we had a place (most likely in the already exist launcher) to add/ share other people's bundles into our game.

**Comment by LMH01** [comment]
It is already possible to share the genres/publishers you have created with your friends. Do do that do the following (in v1.7.1): Click "Share" Menu -> Hover over genre/publisher -> Click Export genre/publisher. In Version v1.8.0 it will be possible to export everything you have created in one go. To import the exported genres/publishers you will have to go into the "mod" menu and under the respective mod you will find the option "import".

Is that what you mean or what do you have in mind?

**Comment by Spontini** [comment]
> It is already possible to share the genres/publishers you have created with your friends. Do do that do the following (in v1.7.1): Click "Share" Menu -> Hover over genre/publisher -> Click Export genre/publisher. In Version v1.8.0 it will be possible to export everything you have created in one go. To import the exported genres/publishers you will have to go into the "mod" menu and under the respective mod you will find the option "import". In version v1.8 it will also be possible to export/import themes.
> 
> Is that what you mean or what do you have in mind?

What i meant is more like a place where i can find bundles from completely strangers

**Comment by LMH01** [comment]
Oh okay, so you mean a platform where you can share your exports with others and install their created exports.
I think the best place to share your created exports would be the [offical Mad Games Tycoon 2 discord server](https://discord.gg/De6uuCC9). Scince Mad Games Tycoon 2 does not have Workshop support. I currently don't plan to create a own website just for that sharing purpose.

**Comment by LMH01** [comment]
I have decided to open the discussions tab for this repository. There you can share your exports.

**Comment by Spontini** [comment]
> Oh okay, so you mean a platform where you can share your exports with others and install their created exports.
> I think the best place to share your created exports would be the [offical Mad Games Tycoon 2 discord server](https://discord.gg/De6uuCC9). Scince Mad Games Tycoon 2 does not have Workshop support. I currently don't plan to create a own website just for that sharing purpose.

Yeah, because if i add genres myself i basically know every perfect settings so it's kinda cheating while playing :P
