### ISSUE TITLE
Adding new gameplay features

### ISSUE THREAD

**Issue by LMH01** [LMH01/MGT2_Mod_Tool#18]

**Comment by Spontini** [comment]
Do you have any ETA for this update? I want to know because i'll start a new game, Imposible Marathon

**Comment by LMH01** [comment]
Feature is done on the dev bench, however it is not yet possible to remove gameplay fetures.

**Comment by LMH01** [comment]
I hope to bring out v1.8.0, where it is possible to add genre/engine features, in the next one or two days.
