### ISSUE TITLE
Add translations to your genre's title and description

### ISSUE THREAD

**Issue by ObiArt** [LMH01/MGT2_Mod_Tool#7]
**Is your feature request related to a problem? Please describe.**
Would be cool if you wanted to share your genres.txt with other people who might not speak your language ie. you created your genre with Russian title and description because you're playing in Russian, and want to share your genres.txt with your friend who speaks English.

**Describe the solution you'd like**
On the first page of genre creation add on option to add translations for your genre.

**Comment by LMH01** [comment]
Thats a good idea. I'm thinking about implementing it.

**Comment by LMH01** [comment]
Added in Version v1.2.0
